//
//  XMenCardViewController.swift
//  Marvel Universe Characters
//
//  Created by user on 1/5/18.
//  Copyright © 2018 Alphonso. All rights reserved.
//

import Foundation
import UIKit

var XMenHeroes = [Hero]()

class XMenCardViewController: UIViewController, UICollectionViewDelegate, UICollectionViewDataSource {
    let Rogue = Hero.init(name: "Rogue", bio: "Rogue is a mutant who formerly possessed the ability to absorb the memories, abilities, personality, and outward physical characteristics of other beings through skin-to-skin contact. Such transfers lasted for 60 times longer than the contact time, with extended contact resulting in the possibility of permanent absorption. No upper limit had been determined for the number of beings Rogue could simultaneously imprint.Upon absorbing another's memories, Rogue also gained any associated emotional responses. Rogue was typically able to control such emotions, however absorbing psyches more powerful than her own resulted in Rogue’s psyche being supplanted.After permanently absorbing the powers of Ms. Marvel (Carol Danvers), Ms. Marvel, Rogue possessed an amalgamated mutant human/alien Kree physiology that granted her a degree of immunity to poisons, and a virtually indestructible body. Rogue also possessed Ms. Marvel's above normal reflexes and psychic seventh sense that enabled her to subconsciously anticipate an opponent’s moves. Whilst Rogue possessed Ms. Marvel's psyche, her double consciousness made her resistant to telepathic probes from even the most powerful mind readers. She also gained Ms. Marvel's incredible strength, and supersonic flight.After absorbing the powers of an alien Skrull, Rogue began to spontaneously reactivate previously absorbed abilities. Rogue could also tap into the residual psychic energy of those she had imprinted to determine their status and to relive past events from their perspective.Recently, Rogue has seemingly permanently absorbed the fire-based powers of Sunfire (Shiro Yoshida), Sunfire.", pic: #imageLiteral(resourceName: "Rogue"))
    
    let Storm = Hero.init(name: "Storm", bio: "Storm (Ororo Monroe) is the descendant of an ancient line of African priestesses, all of whom have white hair, blue eyes, and the potential to wield magic. Xavier explained to Ororo that she was not a goddess, but a mutant, and as such she had a responsibility to use her abilities to help the world just as she had helped the local tribes. Curious, Ororo accepted Xavier's offer, and was given the codename Storm.", pic: #imageLiteral(resourceName: "Storm"))
    
    let Wolverine = Hero.init(name: "Wolverine", bio: "Wolverine is a mutant who possesses the ability to regenerate damaged or destroyed areas of his cellular structure at a rate far greater than that of an ordinary human. The speed at which this healing factor works varies in direct proportion with the severity of the damage Wolverine suffers. For example, he can fully recover from an ordinary gunshot wound in a non-vital area of his body within minutes, but it took him almost two months to fully recover from injuries sustained in a duel with Lord Shingen, which included one from a sword that went all the way through his trunk.Wolverine’s natural healing also affords him virtual immunity to poisons and most drugs, as well as an enhanced resistance to diseases. For example, it is nearly impossible for him to become intoxicated from drinking alcohol. He also has a limited immunity to the fatigue poisons generated by bodily activity, and hence he has greater endurance than an ordinary human. His agility and reflexes are similarly enhanced.In addition, Wolverine’s healing factor provides him with an extended lifespan by slowing the effects of the aging process. Although over a century old, Wolverine is as healthy and physically fit as a man in his prime.Wolverine also possesses superhumanly acute senses, making him capable of seeing things at a maximum distance greater than a normal human’s. His hearing is enhanced in a similar manner, and he is able to recognize people and objects by scent, even if that person or object is hidden. Wolverine can use these enhanced senses to track any creature with an impressive degree of success.Wolverine’s skeleton includes six retractable one-foot long bone claws, three in each arm, that are housed beneath the skin and muscle of his forearms. Wolverine can, at will, release these slightly curved claws through his skin beneath the knuckles on each hand. The skin between the knuckles tears and bleeds, but the blood loss is quickly halted by his healing factor. Wolverine can unsheathe any number of his claws at once, although he must keep his wrists straight at the moment his claws shoot from his forearms into his hands. When unsheathed, the claws are fully within his hands, and thus Wolverine can still bend his wrists. The claws are naturally sharp and tougher than that of normal human bone structure, allowing Wolverine to cut through most types of flesh and natural materials.Despite the extent of his healing factor, Wolverine is not immortal. If the injuries are extensive enough, especially if they result in the loss of vital organs, large amounts of blood, and/or loss of physical form, such as having flesh burned away by fire or acid, Wolverine can die.", pic: #imageLiteral(resourceName: "Wolverine"))
    
   
    
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return XMenHeroes.count
    }
    
    //Cell Config
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell: XMenCardViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! XMenCardViewCell
        
        cell.cellLabel.text = XMenHeroes[indexPath.row].name
        cell.cellTextField.text = XMenHeroes[indexPath.row].bio
        cell.imageCell.image = XMenHeroes[indexPath.row].pic
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let detailController = storyboard?.instantiateViewController(withIdentifier: "XMenHeroController") as! XMenHeroController
        
        detailController.detailImage = XMenHeroes[indexPath.row].pic
        
        showDetailViewController(detailController, sender: collectionView)
        
        //navigationController?.show(detailController, sender: CardViewController.self)
    }
    
    func viewWillAppear() {
        
    }
    
    override func viewDidLoad() {
        XMenHeroes.removeAll()
        XMenHeroes.append(Wolverine)
        XMenHeroes.append(Storm)
        XMenHeroes.append(Rogue)
        
        
        
    }
    
}

